In [4]:
import numpy as np

from sklearn.model_selection import train_test_split

X, y = np.arange(10).reshape((5, 2)), range(5)


X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
list (y)

[0, 1, 2, 3, 4]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(

    X, y, test_size=0.2, random_state=42)

In [8]:
X_train

array([[8, 9],
       [4, 5],
       [0, 1],
       [6, 7]])

In [9]:
X_test

array([[2, 3]])

In [10]:
y_train

[4, 2, 0, 3]

In [11]:
y_test

[1]